.github/workflows/test.yml
.travis.yml

Tests Python 3.5-3.8 on Ubuntu, macOS and Windows. Could also test Python 2.7, but that's covered by Travis CI and will be going away soon.
Example build: https://github.com/hugovk/humanize/actions/runs/35430735

Test Linux, macOS and Windows on GitHub Actions

---

setup.py
tests/time.py

mock is a backport for versions of python < 3.4
Let's use the mock that comes with Python for recent versions of Python 3.x

Use built-in mock from unittest when available (Python 3.4+)

---

humanize/__init__.py

It's also pretty common to use `__version__` to report the module's version, but I didn't want to completely change this ;)

make VERSION match reality

---

tests/test_time.py

Fixes #24, replaces and closes #60.
In addition to the invalid date format, there's another problem with the test, in that the unfixed version passes, when it should fail:
https://travis-ci.com/hugovk/humanize/jobs/280093724
It's making the mistake of using the same logic in the input as in the output, and not testing the output for correctness.
Here's some general advice:
* https://testing.googleblog.com/2014/07/testing-on-toilet-dont-put-logic-in.html
It's passing bad input in:
```python
(date(1982, 6, 27), '%Y.%M.%D')
```
But also then comparing that against bad expected output: 
```python
date(1982, 6, 27).strftime('%Y.%M.%D')
```
```python
>>> from datetime import date
>>> date(1982, 6, 27).strftime('%Y.%M.%D')
'1982.00.06/27/82'
>>> date(1982, 6, 27).strftime('%Y.%M.%d') …
```

Fix invalid date format in test

---

setup.py
tests/test_i18n.py
tests/test_time.py

Includes #88.
* Test `time.naturaldate` with non-dates
* Use freezegun to test with static dates
* Refactor `test_time.py` and format with `black -S`
* Test `i18n.activate` and `deactivate`
https://codecov.io/gh/hugovk/humanize/tree/feae2290057f60056db1c1f035a4a347f41fa7a4

Improve test coverage to 100%

---

.github/workflows/release.yml

Uses https://github.com/actions/create-release to simplify the release process.
When pushing a tag, this will create a corresponding release at https://github.com/jmoiron/humanize/releases.
Note: The body text won't be created as "* TODO" from the config, but "Release [x.y.z]". This has been fixed in the action, but not yet released: https://github.com/actions/create-release/issues/38.

Add GitHub Action to create a release from a tag

---

.pre-commit-config.yaml
.travis.yml
README.md
pyproject.toml
setup.cfg
setup.py
src/humanize/compat.py
src/humanize/filesize.py
src/humanize/i18n.py
src/humanize/number.py
src/humanize/time.py
tests/base.py
tests/test_filesize.py
tests/test_i18n.py
tests/test_number.py
tests/test_time.py
tox.ini

Drop support for EOL Python 2

---

.travis.yml

Something with the new virtualenv is making `3.x-dev` fail on Travis CI.
* https://travis-ci.com/hugovk/humanize/builds/148391816
* https://github.com/pypa/virtualenv/issues/1576
* https://travis-ci.community/t/python-development-versions-no-longer-include-pip/7180
Allow it to fail for now:
* https://travis-ci.com/hugovk/humanize/builds/148419307

Allow 3.9-dev to fail

---

.pre-commit-config.yaml
LICENCE
README.md
setup.cfg
src/humanize/time.py
tests/test_time.py

Fixes #75.
Normally if something is less than a second, `naturaldelta` returns "a moment" and `naturaltime` returns "now".
This adds a `minimum_unit` which can be "milliseconds" or "microseconds" to return something with those units for subsecond values.
For example:
```python
import datetime as dt
from humanize import naturaldelta, naturaltime
delta = dt.timedelta(seconds=4)
print(f"s\tTask took {naturaldelta(delta)} to complete")
print(f"s\t2 subtasks took {naturaldelta(delta / 2)} each to complete")
print(f"s\t1000 subtasks took {naturaldelta(delta / 1000)} each to complete")
print(
f"ms\t1000 subtasks took {naturaldelta(delta / 1000, minimum_unit='milliseconds')} each to complete"
)
print(
f"μs\t1000 subtasks took {naturaldelta(delta / 1000, minimum_unit='microseconds')} each to …
```

Add micro- and millisecond units to naturaldelta and naturaltime

---

.travis.yml

Reverts jmoiron/humanize#103.
The virtualenv/Travis issues have been fixed, let's make sure the code passes on 3.9-dev.
https://travis-ci.com/hugovk/humanize/builds/148808154

Revert "Allow 3.9-dev to fail"

---

.github/labels.yml

GHA: No need to repeat 'changelog' in the name and description

---

README.md
src/humanize/__init__.py
src/humanize/number.py
tests/test_filesize.py
tests/test_number.py
tests/test_time.py

Closes https://github.com/jmoiron/humanize/pull/76.
Same as https://github.com/jmoiron/humanize/pull/76, with merge conflicts resolved and only docstring, formatting changes. Tests essentially the same, rewritten to `@pytest.mark.parametrize`.
Thanks @Thx3r!
TODO

Add scientific notation to string support

---

.github/workflows/release-drafter.yml

Previous attempt in #114 didn't work: it skipped it in my fork and this repo. Let's try this way.

Don't draft releases in forks

---

.github/workflows/test.yml
.travis.yml
tox.ini

Codecov now supports tokenless uploads for GitHub Actions.
https://community.codecov.io/t/whitelist-github-action-servers-to-upload-without-a-token/491/17

GHA: Send coverage to Codecov

---

.github/workflows/lint.yml
.pre-commit-config.yaml
README.md
setup.cfg
tox.ini

* Followup to https://github.com/jmoiron/humanize/pull/134
* Found via byexample (re: https://github.com/byexamples/byexample/issues/116)
* Update some test things
---
* Just one thing left, which I don't think needs to be runnable:
```console
$ byexample -x-shebang 'python:/Library/Frameworks/Python.framework/Versions/3.8/bin/python3 %a' -l python -o '+force-echo-filtering +geometry=24x300' README.md
**********************************************************************
File "README.md", line 171
Failed example:
humanize.i18n.activate("pt_BR", path="path/to/my/portuguese/translation/")
Expected:
<gettext.GNUTranslations instance ...>
Got:
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File …
```

README: Update expected exception when translation not found

---

README.md
src/humanize/__init__.py
src/humanize/time.py
tests/test_time.py

Fixes #48 
* Extend Unit enum to have all the time units handled by `humanize` (years, months, ...)
* Be able to order the time units (`Unit.YEARS < Unit.MONTHS` for example)   
* Implement a `precisedelta` function to represent timedeltas without losing precision (fixes #48, supersedes  #57)
Current limitations:
- The comma `,` is used as separator. It could be easily changed but still we should consider the localization for this.
- The ` and ` is used to join the last item. Translation is required.
- If microseconds are used but seconds, milliseconds and microseconds are suppressed, the microseconds are lost.
Examples:
Return a precise representation of a timedelta
```python
>>> import datetime as dt
>>> from humanize.time import precisedelta
>>> …
```

Function to represent timedeltas without losing precision (precisedelta)

---

.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.gitignore
docs/filesize.md
docs/i18n.md
docs/index.md
docs/number.md
docs/time.md
mkdocs.yml
src/humanize/filesize.py
src/humanize/i18n.py
src/humanize/number.py
src/humanize/time.py
tox.ini

For https://github.com/jmoiron/humanize/issues/139.
* First part for https://github.com/jmoiron/humanize/issues/139: build the docs from the docstrings (deploy to RTD or `gh-pages` follow)
* Update most docstrings to follow the same format (still a few to do, can be updated later)
* Also some `v2` updates to `lint.yml` and `test.yml`
```sh
pip install -U mkdocs mkdocs-material mkdocstrings
mkdocs build
mkdocs serve
```

Build API reference docs from docstrings using MKDocs

---

.readthedocs.yml
README.md
docs/requirements.txt
mkdocs.yml
tox.ini

For https://github.com/jmoiron/humanize/issues/139.
* Follow on from https://github.com/jmoiron/humanize/pull/147
* Most of the second part for https://github.com/jmoiron/humanize/issues/139: deploy to Read the Docs
* https://humanize.readthedocs.io is already registered for this project, and I'll ask for access, but in the meantime I've made https://python-humanize.readthedocs.io to get the config all in order

Deploy docs to Read the Docs

---

src/humanize/i18n.py
tests/test_i18n.py

* Default locale path only is computed when `humanize.i18n.activate` function is called.
* Handle `__file__ is None` and `__file__` not defined cases.  
* Add tests cases increasing code coverage.

Improve default locale path discovering.

---

setup.py

Since the package uses pkg_resources, add an explicit install_requires
for setuptools.  While it is not technically required to install it
right now, it is going to help distribution packagers notice
the necessity of using a runtime dependency (vs the usual build-time
dependency).

Add explicit setuptools dependency for pkg_resources

---

.pre-commit-config.yaml
src/humanize/time.py
tests/test_time.py

This allows having a different point in time to which a value is compared.
Useful if one is dealing with datetimes that are not in the local timezone.
Fixes #55.
* both `naturaldelta` and `naturaltime` now expose an optional `now` parameter
* both methods may now be used with `datetime` objects that are not in the local timezone

Allow custom "now" in naturaldelta and naturaltime

---

src/humanize/filesize.py
src/humanize/number.py
src/humanize/time.py
tox.ini

add a section to "tox.ini" that includes doctests in testing
add doctests to some modules
I noticed that there were already doctests in some of the modules but they were not being tested. I Think it would be great to include them in testing with the added benefit of the doctests showing examples of how to use the modules. 
I got the idea to do this when I found the documentation bug months ago that was patched in [this commit](https://github.com/jmoiron/humanize/commit/15ecb0a778b38925bf8188bd1ca6be95b54ed1cc)

testing/docs: Include doctests in testing

---

src/humanize/time.py
tests/test_time.py

Fixes #159
If the delta is too small to be represented with the minimum unit,
represent it as "0 X" where X is the minimum unit.

Represent with a zero if the delta is too small

---

.github/workflows/test.yml

Temporarily test PyPy3 without tox due to a PyPy3 7.3.2 bug:
* https://foss.heptapod.net/pypy/pypy/-/issues/3331
* https://github.com/tox-dev/tox/issues/1704

GHA: Temporarily toxlessly test PyPy

---

.pre-commit-config.yaml
pyproject.toml
setup.cfg
setup.py

* apply setup-py-upgrade
* move setuptools_scm config to pyproject.toml

Apply setup-py-upgrade

---

.github/workflows/test.yml

Reverts jmoiron/humanize#174
GHA now has PyPy 7.3.3 and we can test it on Windows with tox: https://github.com/actions/setup-python/issues/163#issuecomment-739907048

Revert "GHA: Temporarily toxlessly test PyPy"

---

.pre-commit-config.yaml
setup.cfg
src/humanize/__init__.py
src/humanize/i18n.py
src/humanize/number.py
tests/test_filesize.py
tests/test_i18n.py
tests/test_number.py
tests/test_time.py
tox.ini

Fixes #177.
* Add internationalisation to `intcomma`
* There's a mapping of locales to thousands separators in `src/humanize/i18n.py`
* Only `fr_FR` -> ` ` added now, and defaults to `,`
* This may be refactored to another file
* Also some pre-commit/isort updates

Internationalise intcomma and add fr_FR

---

src/humanize/__init__.py
src/humanize/number.py
tests/test_number.py

This PR adds function `clamp` to `humanize.number`.
`clamp` take a number and format, and returns the formatted number clamped between a floor and a ceiling.
I believe that this is a good addition, as often there are ranges above or below which precision doesn't really matter. For example, when discussing percentages writing "under 1%" can be much more understandable than writing "0.984%".
`clamp` also plays very well with the rest of the `humanize.number` package, as `format` can be a function.
For example, you can pass `humanize.intword` to format, and the output will be clamped and formatted.
* `value`: number to format
* `format` (default = `"{:}"`: Can be a string such that `format.format(value)` *or* a callable function like `humanize.intword`
* `floor` (default = `None` ): If …

Adds humanize.number.clamp

---

.pre-commit-config.yaml
setup.cfg
src/humanize/time.py

Fixes #194.
* `enum`'s `__repr__()` and `__str__()` are changing in 3.10, so use `.name` for the doctests
* https://docs.python.org/3.10/whatsnew/3.10.html#enum
```pycon
Python 3.9.4 (v3.9.4:1f2e3088f3, Apr  4 2021, 12:32:44)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from humanize.time import Unit
>>> repr(Unit.HOURS), str(Unit.HOURS), Unit.HOURS.name
('<Unit.HOURS: 4>', 'Unit.HOURS', 'HOURS')
>>>
```
```pycon
Python 3.10.0a7+ (heads/master:ea9b2d6, Apr 10 2021, 19:11:52) [Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from humanize.time import Unit
>>> repr(Unit.HOURS), str(Unit.HOURS), Unit.HOURS.name …
```

Fix tests for Python 3.10

---

src/humanize/time.py

This is so consumers of this library can get good feedback based on return types.  
`tox` seems happy with the changes made.
(no issue currently open for this).

Add type hints for all exposed natural* functions

---

src/humanize/locale/ca_ES/LC_MESSAGES/humanize.po
src/humanize/locale/de_DE/LC_MESSAGES/humanize.po
src/humanize/locale/es_ES/LC_MESSAGES/humanize.po
src/humanize/locale/fa_IR/LC_MESSAGES/humanize.po
src/humanize/locale/fi_FI/LC_MESSAGES/humanize.po
src/humanize/locale/fr_FR/LC_MESSAGES/humanize.po
src/humanize/locale/id_ID/LC_MESSAGES/humanize.po
src/humanize/locale/it_IT/LC_MESSAGES/humanize.po
src/humanize/locale/ja_JP/LC_MESSAGES/humanize.po
src/humanize/locale/ko_KR/LC_MESSAGES/humanize.po
src/humanize/locale/nl_NL/LC_MESSAGES/humanize.po
src/humanize/locale/pl_PL/LC_MESSAGES/humanize.po
src/humanize/locale/pt_BR/LC_MESSAGES/humanize.po
src/humanize/locale/pt_PT/LC_MESSAGES/humanize.po
src/humanize/locale/ru_RU/LC_MESSAGES/humanize.po
src/humanize/locale/sk_SK/LC_MESSAGES/humanize.po
src/humanize/locale/tr_TR/LC_MESSAGES/humanize.po
src/humanize/locale/uk_UA/LC_MESSAGES/humanize.po
src/humanize/locale/vi_VI/LC_MESSAGES/humanize.po
src/humanize/locale/zh_CN/LC_MESSAGES/humanize.po
src/humanize/number.py
tests/test_i18n.py

Closes #203
* Add `gender` argument for `humanize.ordinal`
* Rebuild locales to support ordinals by gender using message contexts
* Adds proper translations for `es_ES`, `fr_FR`, `it_IT`, `pt_BR` and `pt_PT`. For the other languages these translations have been left as it is, so this change will not break previous translations.

Add gender support for ordinals

---

src/humanize/locale/fa_IR/LC_MESSAGES/humanize.po

As the title suggests, the pull request defines the missing strings in the `.po` file for Persian.

Add missing strings for Persian

---

RELEASING.md

For https://github.com/jmoiron/humanize/issues/211.
* The 3.7.0 release didn't include translation binaries because I missed a step in the release checklist
* Let's include the step in the previous chunk to prevent this
* Longer term solution is to automate deploys, for that I will need admin permissions for this repo

Update release checklist so translation binaries aren't forgotten

---

README.md
src/humanize/locale/sl_SI/LC_MESSAGES/humanize.po

* Slovenian (sl_SI) locale added

Add Slovenian translation

---

src/humanize/locale/vi_VN/LC_MESSAGES/humanize.po

Fixes #
* Move folder `vi_VI` to `vi_VN`, this is the proper locale name for Vietnamese
* Update some missing translations

Move vi_VI to vi_VN and update some translations

---

.github/workflows/test.yml

Fixes #
Added python 3.10 to test yml for github CI
* Updated to 3.10 instead of 3.10-dev

Update github CI test with python 3.10 for new release

---

setup.cfg
setup.py
src/humanize/__init__.py

pkg_resources use a lot of memory and after introducing importlib.metadata in 3.8 looks obsolete. So let's change way to get package version and get rid of pkg_resources import.

Use importlib.metadata to get package version instead of pkg_resources.get_distribution to decrease memory consumption

---

.pre-commit-config.yaml

Fixes #228
* Removed a max-py-version from yaml configuration

Remove redundant --max-py-version=3.10 from pre-commit

---

RELEASING.md

* Running `setup.py anything` is discouraged
* Use `python -m build` instead, it creates both sdist and wheel by default
* https://packaging.python.org/guides/distributing-packages-using-setuptools/#packaging-your-project
* I used this for https://github.com/jmoiron/humanize/releases/tag/3.12.0

Update release checklist to use python-build

---

.github/workflows/test.yml

* `pypy3` has started failing for macOS on GHA (https://github.com/jmoiron/humanize/pull/235#issuecomment-958846008):
```
Run actions/setup-python@v2
Error: PyPy 3.6 not found
```
* `pypy3` isn't explicitly documented at https://github.com/actions/setup-python#specifying-a-pypy-version
* Let's explicitly test the latest `pypy-3.8`. We could test `pypy-3.6` and `pypy-3.7` but 3.6 is EOL next month and testing a single PyPy should be enough.

Specify pypy-3.8 on GHA

---

README.md
src/humanize/__init__.py
tests/test_humanize.py
tests/test_i18n.py
tests/test_number.py
tests/test_time.py
tox.ini

* `VERSION` was inadvertently removed in https://github.com/jmoiron/humanize/pull/227 but not yet released
* Let's reinstate it
* But as it's non-standard and we've had the standard `__version__` since humanize 1.0 (Feb 2020), let's deprecate it and remove it in the next major bump
* We can use the technique for deprecating constants only available in Python 3.7+, which is fine as the next major bump will also drop 3.6 (https://github.com/jmoiron/humanize/pull/239)

Reinstate `VERSION` and deprecate

---

src/humanize/i18n.py
src/humanize/number.py
src/humanize/time.py
tests/test_time.py

These functions (and the enum) are listed on the documentation but are not available from the root `humanize` package.
This change makes the private functions private by prepending their names with an underscore. In order to make this change backwards compatible, we provide aliases for the functions under the old names. These aliases will emit deprecation warnings if called. The aliases are removed in samueljsb/humanize#1.
This fixes #225.

Deprecate private functions

---

src/humanize/time.py

Temporary fix for #242.
* Comment out the warning to avoid warning during `import humanize`
```console
$ python3 -W error -c 'import humanize'
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/humanize/__init__.py", line 17, in <module>
from humanize.time import (
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/humanize/time.py", line 75, in <module>
class Unit(Enum, metaclass=_UnitMeta):
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/enum.py", line 215, in __new__
enum_class._member_names_ = []               # names in definition order
File …
```

Temporarily comment out to avoid warning during `import humanize`

---

src/humanize/time.py
tests/test_time.py

Related to #245
Presently, it is hard to read very long times because the largest time denomination that `humanize` includes is years. In this pull request, `humanize.intcomma()` is now used to format the number of years returned by `naturaldelta()` and `precisedelta()`.
Alternate approaches considered include:
1. Adding a `millennia` denomination, but this would require all translations to be updated.
2. Using the `{:n}` format specifier along with the standard `locale` module, but locale has inconsistent behavior across platforms and `humanize` already uses an internal localization module.

Use humanize.intcomma to format years in time module

---

src/humanize/time.py

Related to #247, but does not close.
Adds deprecation warnings for `naturaldelta(..., when)` because this parameter does not make sense for a time*delta*.
Didn't add test because it seems silly to test for the presence of deprecation warnings that will only be around until the next release.

Deprecate `when` parameter of `naturaldelta`

---

src/humanize/i18n.py
src/humanize/time.py

Removes aliases for deprecated functions introduced in #234.
This completes the deprecation of these public functions (the functions are still accessible as private members of their modules).

Remove deprecated private function aliases

---

.github/workflows/docs.yml
.github/workflows/labels.yml
.github/workflows/lint.yml
.github/workflows/release-drafter.yml
.github/workflows/test.yml
.pre-commit-config.yaml
pyproject.toml
setup.cfg
src/humanize/number.py
src/humanize/time.py
tests/test_filesize.py
tests/test_number.py
tox.ini

Python 3.6 is (almost) EOL:
| cycle | latest |  release   |    eol     |
|:------|:-------|:----------:|:----------:|
| 3.10  | 3.10.0 | 2021-10-04 | 2026-10-04 |
| 3.9   | 3.9.9  | 2020-10-05 | 2025-10-05 |
| 3.8   | 3.8.12 | 2019-10-14 | 2024-10-14 |
| 3.7   | 3.7.12 | 2018-06-27 | 2023-06-27 |
| 3.6   | 3.6.15 | 2016-12-23 | 2021-12-23 |
Also update some other CI config like using actions/setup-python's own pip caching instead of using actions/cache directly.

Drop support for Python 3.6
